sylius_grid:
    templates:
        action:
            create_gift_card: "@SetonoSyliusGiftCardPlugin/Admin/GiftCard/Grid/Action/create.html.twig"
            delete_conditional: "@SetonoSyliusGiftCardPlugin/Admin/GiftCard/Grid/Action/delete_conditional.html.twig"
            gift_card_balance: "@SetonoSyliusGiftCardPlugin/Admin/GiftCard/Grid/Action/gift_card_balance.html.twig"
            list_conditional: "@SetonoSyliusGiftCardPlugin/Admin/GiftCard/Grid/Action/list_conditional.html.twig"
    grids:
        setono_sylius_gift_card_admin_gift_card:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_gift_card.model.gift_card.class%"
                    repository:
                        method: createListQueryBuilder
            sorting:
                createdAt: desc
            limits: [25, 50, 100]
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                amount:
                    type: twig
                    label: setono_sylius_gift_card.ui.amount
                    path: .
                    sortable: amount
                    options:
                        template: "@SetonoSyliusGiftCardPlugin/Admin/GiftCard/Grid/Field/amount.html.twig"
                initialAmount:
                    type: twig
                    label: setono_sylius_gift_card.ui.initial_amount
                    path: .
                    sortable: initialAmount
                    options:
                        template: "@SetonoSyliusGiftCardPlugin/Admin/GiftCard/Grid/Field/amount.html.twig"
                channel:
                    type: twig
                    label: sylius.ui.channel
                    sortable: channel.code
                    options:
                        template: "@SyliusAdmin/Order/Grid/Field/channel.html.twig"
                currencyCode:
                    type: string
                    label: sylius.ui.currency
                    sortable: ~
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
                createdAt:
                    type: datetime
                    label: sylius.ui.created
                    sortable: ~
                    options:
                        format: d-m-Y
                order:
                    type: twig
                    label: sylius.ui.order
                    path: orderItemUnit
                    options:
                        template: "@SetonoSyliusGiftCardPlugin/Admin/GiftCard/Grid/Field/item_units_order.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code]
                channel:
                    type: entity
                    label: sylius.ui.channel
                    form_options:
                        class: "%sylius.model.channel.class%"
                amount:
                    type: money
                    label: sylius.ui.amount
                    options:
                        currency_field: currencyCode
                enabled:
                    label: sylius.ui.enabled
                    type: boolean
            actions:
                main:
                    balance:
                        type: gift_card_balance
                    create:
                        type: create_gift_card
                item:
                    list_orders:
                        type: list_conditional
                        label: setono_sylius_gift_card.ui.list_orders
                        options:
                            visible: resource.hasAppliedOrders
                            link:
                                route: setono_sylius_gift_card_admin_gift_card_orders_index
                                parameters:
                                    id: resource.id
                    delete:
                        type: delete_conditional
                        options:
                            visible: resource.isDeletable
