setono_sylius_gift_card_admin_gift_card:
    resource: |
        alias: setono_sylius_gift_card.gift_card
        section: admin
        only: [index, delete, bulkDelete]
        templates: SyliusAdminBundle:Crud
        redirect: index
        grid: setono_sylius_gift_card_admin_gift_card
        vars:
            all:
                subheader: setono_sylius_gift_card.ui.gift_card
                templates:
                    form: "@SetonoSyliusGiftCardPlugin/Admin/GiftCard/_form.html.twig"
            index:
                icon: 'gift'
    type: sylius.resource

# todo what is this route doing?
setono_sylius_gift_card_admin_gift_card_create_for_channel:
    path: /gift-cards/create
    methods: [GET]
    defaults:
        _controller: sylius.controller.channel:indexAction
        _sylius:
            repository:
                method: findAll
            template: "@SetonoSyliusGiftCardPlugin/Admin/GiftCard/create.html.twig"
            permission: true

setono_sylius_gift_card_admin_gift_card_create:
    path: /gift-cards/create/{channelCode}
    methods: [GET, POST]
    defaults:
        _controller: setono_sylius_gift_card.controller.gift_card:createAction
        _sylius:
            factory:
                method: createForChannel
                arguments:
                    channel: "expr:service('sylius.repository.channel').findOneByCode($channelCode)"
            template: SyliusAdminBundle:Crud:create.html.twig
            grid: setono_sylius_gift_card_admin_gift_card
            section: admin
            redirect:
                route: setono_sylius_gift_card_admin_gift_card_index
            permission: true
            vars:
                route:
                    parameters:
                        channelCode: $channelCode
                templates:
                    form: "@SetonoSyliusGiftCardPlugin/Admin/GiftCard/_form.html.twig"

setono_sylius_gift_card_admin_gift_card_orders_index:
    path: /gift-cards/{id}/orders
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.order:indexAction
        _sylius:
            vars:
                route:
                    parameters:
                        id: $id
            template: SyliusAdminBundle:Crud:index.html.twig
            grid: setono_sylius_gift_card_admin_gift_card_order
            section: admin
            permission: true

setono_sylius_gift_card_admin_gift_card_balance:
    path: /gift-cards/balance
    methods: [GET]
    defaults:
        _controller: setono_sylius_gift_card.controller.action.gift_card_balance
        _sylius:
            section: admin
